gnachman/iterm2-website

source/misc/bash_startup.in
Fixes iTerm2-Issue #3526 "iTerm2 Shell Integrations affect STDOUT of piped sub-shells"
Issue: https://gitlab.com/gnachman/iterm2/issues/3526
without this fix consider the following test:
``` bash
true | wc -c             # outputs: 0
(true) | wc -c           # outputs: 8
(true) | true | wc -c    # outputs: 0
(true) | (true) | wc -c  # outputs: 8
(true | true) | wc -c    # outputs: 16
```
=> Fix Shell Integration: Issue with piped sub-shells

source/misc/install_shell_integration.sh
References to this script point to the HTTPS version, but subsequently
downloaded resources are delivered over plain HTTP which could make the
user vulnerable to MITM code execution. I would additionally recommend
making these resources 500 if requested over plain HTTP.
=> Load executable scripts over TLS to avoid MITM

source/misc/install_shell_integration.sh
If $HOME dir contains spaces "test" command fails with message "binary operator expected"
=> Fix "expected binary operator" bug.

source/badges.md
This is currently breaking and causes the link to go to `https://www.iterm2.com/github.com/gnachman/iTerm2`.
=> Use absolute link to GitHub repository URL

source/misc/bash_startup.in
These updates improve the hostname detection in the shell integration script.
This pull consists of two commits:
* the first is for OpenBSD, and corrects hostname detection by assigning the hostname with `cat /etc/myname` instead of `hostname -f` [issue #4225](https://gitlab.com/gnachman/iterm2/issues/4225)
* the second is for Linux hosts (without domains specified), and adjusts their hostname value for proper function in mDNS environments [issue #4194](https://gitlab.com/gnachman/iterm2/issues/4194)
I've made a [Google Docs Spreadsheet] (https://docs.google.com/spreadsheets/d/1KtAXPnntiEDNwyQbOtOD6-1sxatKgxgElSRvzgSrGzg/) which summarizes the results of different hostname identification methods on a variety of host types and linux distros.
The next step is to get these changes ported …
=> Improved hostname detection - initial changes

source/misc/zsh_startup.in
iTerm2's shell integration had been reporting return codes properly using bash, but not with zsh, so I took a look at it.
=> Fix process return code reporting for zsh shell integration

source/misc/install_shell_integration.sh, source/misc/install_shell_integration_and_utilities.sh
Using '==' is a bashism, so running install_shell_integration.sh or install_shell_integration_and_utilities.sh with zsh gives a rather confusing error message:
% zsh ./install_shell_integration_and_utilities.sh
./install_shell_integration_and_utilities.sh:15: = not found
Using a single '=' to test for equality is more portable, so use that instead.
=> For shell equality tests, use '=' instead of '=='

source/misc/fish_startup.in
Fish shell >=2.4.0 requires that function options be specified after the function name.
=> Update fish_startup.in to move "-v" option

source/_includes/documentation-general-usage.md, source/_includes/documentation-menu-items.md, source/_includes/documentation-preferences.md
Just found a couple little pecadillos as I was reading the docs. There may be a few more, but these were the ones that jumped out at me.
=> Fixing some typos and missing links in documentation

source/misc/fish_startup.in
This rewrites it into more idiomatic fish, and greatly simplifies it in the process.
I manually tested this on my machine, and it seems to work, even with multiline prompts and printf format strings. To reproduce what I have, just append `printf "\n\n%%s > \n"` to your `fish_prompt` function.
_Side note:_
It would be nice if this was part of the main app instead of here, which also would allow to ship the current version in the app. So you could `source /Applications/iTerm.app/Contents/integration/iterm.fish` or something similar.
=> Simplify the fish_prompt function

source/misc/bash_startup.in, source/misc/fish_startup.in, source/misc/tcsh_startup.in, source/misc/zsh_startup.in
OpenBSD and NetBSD don’t have the -f option to the hostname command. Check if the command completed successfully, if not, then set iterm2_hostname to the output of the hostname command with no command line options.
Resolves #41.
=> Fix hostname error for *BSD flavors

source/utilities/it2check, source/utilities/it2getvar
This copies the more robust handling of stty from it2ul to it2check and it2getvar. Trapping the stty restoration on EXIT means we're covered in all situations that might cause the script to exit early, not just the user hitting Ctrl+C, and means we don't need to remember to do it in the script's happy path. Accordingly, this fixes an issue in which it2getvar did not restore the stty settings if execution completed without issue.
=> Improve stty handling in it2check and it2getvar

source/shell_integration/bash
bash-preexec.sh [has a check early on][check] to make sure it hasn't been sourced elsewhere and returns if it has. To avoid this resulting in the bash integration script quitting early, we wrap it in a function.
[check]: https://github.com/gnachman/iterm2-website/blob/f58ce5bd6183d994797b1e6286ef8ac8c9f44233/source/shell_integration/bash#L73-L76
=> Wrap included bash-preexec.sh in a function

source/_includes/3.0/documentation-shell-integration.md, source/_includes/documentation-shell-integration.md
Match to the [actual behavior](
https://github.com/gnachman/iTerm2/blob/f8a5930b5c47fa6420f423fcb33320029abdcd5b/sources/SCPFile.m#L194-L196), which is correct.
=>  Correct ssh config path in docs

source/utilities/it2git
Check to see if PWD is in a git repo before running
subsequent commands that are only useful within a git
repo.
=> it2git: short-circuit if we are not in a git repo.

source/utilities/imgcat
Improved formatting with `shfmt -i=4 -s` https://github.com/mvdan/sh#shfmt to ensure that it passes shellcheck https://github.com/koalaman/shellcheck#shellcheck---a-shell-script-static-analysis-tool.
=> Improve imgcat formatting

source/shell_integration/fish
Introduce generic `iterm2_check_function` helper.
Fix inconsistent indentation and remove unnecessary quotes.
=> [fish shell integration] refactor `fish_mode_prompt` check

source/patrons.txt
There is a cosmetic issue in the `iTermAboutWindow` where line spacing, the font, and/or other styling gets thrown off by unique characters in the patrons list, starting with `＊` in `Emily St＊` and ending with `ř` in `Ondřej Surý` :
This string appears to be fetched etc from the static file `patrons.txt` on `iterm2-website`. 
This pull request simply removes and/or updates the unique characters. Submitting as a draft because I have been unable[1] to successfully build iTerm2 locally with Xcode to test this change by linking to a local edited version of `patrons.txt`.
No doubt there is more than one way to resolve this. If I could run locally, would be happy to tinker with `iTermAboutWindowController.m` to come up with something more robust and future-proof (plus work on some other open …
=> AboutWindow bug fix

source/_includes/documentation-utilities.md
The example block for it2dl was wrongly located so I moved to where it belongs, and improved a bit other examples and usages.
=> Moved it2dl example block and fixed other details

source/_includes/3.0/documentation-menu-items.md, source/_includes/3.1/documentation-toolbelt-menu.md, source/_includes/3.2/documentation-toolbelt-menu.md, source/_includes/3.3/documentation-toolbelt-menu.md, source/_includes/3.4/documentation-toolbelt-menu.md, source/_includes/3.5/documentation-toolbelt-menu.md, source/_includes/documentation-toolbelt-menu.md
Found a typo in the documentation, corrected it in the `.md` files. No other changes.
=> Fixed a typo: Tolbelt -> Toolbelt
